### PR TITLE
Add a node spin up benchmark application

### PR DESCRIPTION
**Pull request by justusc**
This application tests the time required to spin up a compute node with a new model. The input and output are JSON files. An example input is included in this PR, which includes all Together public models on Hugging Face.

The commands to kick off the the benchmark are in the log file.
```
$ python3 ml_load_bench.py -i benchmark_input.json -o benchmark_results.json -d cuda:4
```

There are 3 cli arguments
1. input file `-i <input file path>`
2. output file `-o <output file path>`
3. GPU to run on `-d cuda:<id>`

The input file is a JSON file with a name and the model path. The sample I provide in the PR request is:
```
{
    "GPT-NeoXT-Chat-Base-20B": "togethercomputer/GPT-NeoXT-Chat-Base-20B",
    "Pythia-Chat-Base-7B": "togethercomputer/Pythia-Chat-Base-7B",
    "GPT-JT-Moderation-6B": "togethercomputer/GPT-JT-Moderation-6B",
    "GPT-JT-6B-v1": "togethercomputer/GPT-JT-6B-v1",
    "GPT-JT-6B-v0": "togethercomputer/GPT-JT-6B-v0"
}
```

The output is a json file with the timings for:
1. tokenizer download time
2. tokenizer load time
3. model download time
5. model load to RAM time
6. model transfer to GPU time
7. inference time ( input is "hello, world!")
8. total time (sum of all the above)

An example of the output is:
```
{
    "GPT-NeoXT-Chat-Base-20B": {
        "tokenizer_download_time": 1.2006566524505615,
        "tokenizer_load_time": 0.10877585411071777,
        "model_download_time": 442.35090947151184,
        "model_load_to_ram_time": 412.0813686847687,
        "model_transfer_to_gpu_time": 8.284619092941284,
        "inference_time": 0.9776885509490967,
        "total_time": 865.0040183067322
    }
}
```

[Planning#405](https://github.com/orgs/togethercomputer/projects/2/views/10?pane=issue&itemId=24918344)

### CODE REVIEW

**Comment by adamsch1** [comment]
LGTM - we should probably run more than one inference to eliminate warmup, like default to I dunno 25 times maybe?  Have a param to override.

**Review by adamsch1 — APPROVED** [review]
LGTM - we should probably run more than one inference to eliminate warmup, like default to I dunno 25 times maybe? Have a param to override.

**Comment by adamsch1** [comment]
Can you dump the output into a notion doc? Would be neat to see.

**Comment by justusc** [comment]
I have no problem making the change. However, the purpose is not to measure the inference time when serving results. It is to measure the spin up time; how long does it take to load a new model and to be able to get the first response.

If you still want to test inference latency after warmup, I can add that as an additional timing.

**Review by justin-together — APPROVED** [review]

**Comment by csris** [comment]
> If you still want to test inference latency after warmup, I can add that as an additional timing.

I like the idea of adding inference latency as an additional timing. Can you file an issue for that in this repo to track it?

**Comment by justusc** [comment]
> > If you still want to test inference latency after warmup, I can add that as an additional timing.
>
> I like the idea of adding inference latency as an additional timing. Can you file an issue for that in this repo to track it?

I have already made the requested change for this branch. I will be pushing it up shortly.

**Comment by csris** [comment]
Even better!

**Pull request merged**
