### PR TITLE
Add argument to offload model from memory to disk

### PR DESCRIPTION
**Pull request by orangetin**
Off-load the pre-trained model from memory to disk as mentioned in #52 

Changes:
- Added argument for off-load directory
- Added 'accelerate' dependency (device_map requires it)

### CODE REVIEW

**Comment by csris** [comment]
Looks good to me! Thanks, @orangetin. @LorrinWWW, can you also review?

**Review by csris — APPROVED** [review]

**Comment by orangetin** [comment]
I'm currently testing the same thing for inference/bot.py and seeing if that helps with the memory load when loading the model. Should I modify this PR once I've tested that too or should I make a new PR for that?

**Comment by orangetin** [comment]
Sorry. Had to undo commits.

**Comment by csris** [comment]
No problem. Do you mind squashing these commits and force pushing to this branch?

**Review by LorrinWWW — APPROVED** [review]
it looks good to me!

**Comment by orangetin** [comment]
> No problem. Do you mind squashing these commits and force pushing to this branch?

Done

**Pull request merged**
