### PR TITLE
Fix cache issue

### PR DESCRIPTION
**Pull request by orangetin**

### CODE REVIEW

**Review by adamsch1 — COMMENTED** [review]
LGTM

**Review by adamsch1 — COMMENTED** [review]
LGTM

**Review by adamsch1 — APPROVED** [review]

**Comment by csris** [comment]
Why was this necessary?

**Comment by orangetin** [comment]
@csris 
 https://github.com/togethercomputer/planning/issues/1255#issuecomment-1635266751

**Comment by csris** [comment]
Thanks. Please link PRs and Issues in the future: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Pull request merged**
