### PR TITLE
fixed #36, Fixed syntax Error

### LINKED ISSUE #36: Exception in prepare.py
python data/OIG/prepare.py
  File "data/OIG/prepare.py", line 27
    gzip.open(f, 'rb') as infile, 
                       ^
SyntaxError: invalid syntax

Tell me why, thank you!

### PR DESCRIPTION
**Pull request by adilaxmdv**
I think Its fixed . Test and accept!
Good day..

### CODE REVIEW

**Comment by csris** [comment]
Python 3.10 actually introduced grouping context managers with parentheses. See [the documentation for the with statement](https://docs.python.org/3.10/reference/compound_stmts.html#the-with-statement). What version of Python are you using?

**Comment by adilaxmdv** [comment]
> Python 3.10 actually introduced grouping context managers with parentheses. See [the documentation for the with statement](https://docs.python.org/3.10/reference/compound_stmts.html#the-with-statement). What version of Python are you using?

python2 xd

**Comment by csris** [comment]
This repo definitely requires python3 even with this patch.

**Comment by adilaxmdv** [comment]
@csris  okay thanks good day

**Comment by csris** [comment]
Thank you for the PR!

**Pull request closed without merging**
