### PR TITLE
`convert_to_hf_gptneox` adds support to other neox models

### PR DESCRIPTION
**Pull request by LorrinWWW**
Previous conversion code assumes the model is neox-20b, and some config is hard-coded, i.e. 44 layers.
(also added a fp16 option.)

example:
```sh
python tools/convert_to_hf_gptneox.py \
    --config-name EleutherAI/pythia-6.9b-deduped \
    --ckpt-path ${PATH_CKPTS}/checkpoint_100 --save-path pythia-6.9b-finetuned \
    --n-stages 4 --n-layer-per-stage 8 --fp16
```

### CODE REVIEW

**Review by csris — APPROVED** [review]

**Comment by ETERNALBLUEbullrun** [comment]
Would use (plus help with issues,) but for the lack of support for regular GPT models.

**Comment by csris** [comment]
We need to update the README as well. @LorrinWWW, can you do that?

**Comment by LorrinWWW** [comment]
@csris Sure I will do that

**Comment by LorrinWWW** [comment]
Done

**Comment by 814007450** [comment]
谢谢，我已收到您的来信。Thank you！I have received your letter.ありがとう！電子メールを受信しました！

**Pull request merged**
